### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by srnyx** [FoundationGames/EnhancedBlockEntities#11]
1. Does this still work with [Expanded Storage](https://www.curseforge.com/minecraft/mc-mods/expanded-storage-fabric)? With [FastChest](https://www.curseforge.com/minecraft/mc-mods/fastchest), it removes the textures added by [Expanded Storage](https://www.curseforge.com/minecraft/mc-mods/expanded-storage-fabric) on the chests.
2. Does this change anything about beds like [Better Beds](https://modrinth.com/mod/better-beds) does?

**Comment by FoundationGames** [comment]
First of all, I would rather you not ask questions here. Issues are for suggestions, to-do, or bugs
1. I never knew that FastChest did anything with ExpandedStorage. I can't tell if you mean they are incompatible, or if FastChest optimizes ES.
2. It will, soon. I will try to use the same or similar format to BB so that resource packs can translate over.

Closed - not an issue

**Comment by srnyx** [comment]
> First of all, I would rather you not ask questions here. Issues are for suggestions, to-do, or bugs
> 
> 1. I never knew that FastChest did anything with ExpandedStorage. I can't tell if you mean they are incompatible, or if FastChest optimizes ES.
> 2. It will, soon. I will try to use the same or similar format to BB so that resource packs can translate over.
> 
> Closed - not an issue

Sorry, I saw someone else ask questions here, and I didn't know where else to ask.
1. https://github.com/NinjaPhenix/FabricMods/issues/87
2. Alright, thank you
