### ISSUE TITLE
Chests blurry when looking from a distance

### ISSUE THREAD

**Issue by Badinek** [FoundationGames/EnhancedBlockEntities#186]
Hello,
chests look blurry when youre looking from about 4-20 blocks away.
Theres also this weird line on top of doublechests separating the two blocks.
It doesnt look very nice so i would appreciate if you fixed this issue.
![javaw_FAa2QOgxKh](https://github.com/FoundationGames/EnhancedBlockEntities/assets/74152061/08bb2bc9-0dc2-4901-9dd5-6cc6a82f49fb)
![javaw_lmj7vfjnFq](https://github.com/FoundationGames/EnhancedBlockEntities/assets/74152061/7016c2c2-0909-4b81-804c-7972e26ef1d8)
The shulker models also have a visual bug. the part where the top of shulker goes up has small holes.
![javaw_vq2jYKarLe](https://github.com/FoundationGames/EnhancedBlockEntities/assets/74152061/17e90099-4a1f-4566-bcbc-02f5cc999294)
![javaw_sDmYcrkOmQ](https://github.com/FoundationGames/EnhancedBlockEntities/assets/74152061/ee39483e-cf59-4eda-9c2f-b52b17d7d664)

Using your optimization resource pack seems to fix neither issue.

**Comment by muzikbike** [comment]
This appears to be due to mipmapping, which isn't a thing for chest blocks in vanilla but gets applied to them with this mod as a consequence of them using proper block models.

**Comment by muzikbike** [comment]
Actually, it probably does exist for chests in vanilla. No idea why I said the above, that atlas has mipmapped versions.

**Comment by FoundationGames** [comment]
Mipmapping is a vanilla feature and the line on top of chests is an unavoidable artifact of mipmapping
I don't plan on adding an option to generate mipmap padding for the chest texture, since texture generation in this mod is already causing compatibility issues with some mods on Quilt
The crease on shulker boxes seems to be a float precision issue and I cannot fix that without stretching the model and instead creating a z-fighting issue (and, this is more noticeable when using Sodium, for reasons beyond my control)
