### ISSUE TITLE
Animation Bug on Servers

### ISSUE THREAD

**Issue by Mouy07** [FoundationGames/EnhancedBlockEntities#43]
![2021-07-26_18 45 46](https://user-images.githubusercontent.com/88009582/127073363-de98d651-b84b-4a85-ae50-871ac30fb8f9.png)

When playing on servers, the lid opens and stays closed at the same time. This happens both with and without Sodium. It also happens on both Fabric and vanilla servers. It doesn't happen in singleplayer.

**Comment by piuvas** [comment]
I would like to add a bit of information on my experience with the issue.

I assume the opening and closing animation are sometimes overlapping. It happens based around position and/or angle, since moving while the animation is active may correct it.

Without sodium, the bug seems to occur in about 5% of my tests.
With sodium, around 90%.

I haven't experience any differences regarding singleplayer or multiplayer.

**Comment by FoundationGames** [comment]
I know exactly why the issue occurs, and what aspects of the code causes it. It's related to timing chunk rebuilds so the chest can switch between its closed and lid-less model. Unfortunately laggy chunk rebuilds can affect the timing, so I need to find a way to circumvent that.

**Comment by IJustWantANamePlease** [comment]
I am experiencing the same bug, but for me it happens on both multiplayer and singleplayer.

**Comment by FoundationGames** [comment]
should be completely fixed in 0.5
