### ISSUE TITLE
Better Beds useless?

### ISSUE THREAD

**Issue by timelady-victorious** [FoundationGames/EnhancedBlockEntities#8]
does this mod render (lol) [better beds](https://modrinth.com/mod/better-beds) useless? Is better bed's resource pack compatibile with this mod, without using Better Beds?

**Comment by FoundationGames** [comment]
EBE does not support beds _**yet**_.
When it does, I can surely try to match Better Beds' model format so that resource packs will be compatible.
The goal of this is not to make other mods obsolete or useless, there may be very specific use cases where you'd rather use Better Beds (if you don't want chests or any of the other blocks revamped by this mod).

**Comment by FoundationGames** [comment]
Closed - Question, not issue
